### ISSUE TITLE
Algolia reindex script tmp index move takes a long time.

### ISSUE THREAD

**Issue by viperfx** [algolia/algoliasearch-django#291]
Django version: Django==2.2.8
Algolia Django integration version: algoliasearch-django==1.7.1
Algolia Client Version: algoliasearch==1.20.0
Language Version: english

### Description
When running the reindex script, I notice the following happening:

- 5k records pushed to a `_tmp` index
- There are more than 5k records, but only 5k is added. Why is that? 
- The real index configured gets added records very very slowly (we are talking like 1 a minute)

Is there something wrong with my setup?

**Comment by tkrugg** [comment]
Hi @viperfx 

> - 5k records pushed to a _tmp index
> - The real index configured gets added records very very slowly (we are talking like 1 a minute)

We reindex to a temporary index instead of directly to the target index to avoid the situation where your target index is empty or half filled. We refer to this in our docs as [Atomic reindexing](https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/in-depth/asynchronicity-and-when-to-wait-for-tasks/#atomic-reindexing) or [Zero-downtime reindexing](https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/in-depth/the-different-synchronization-strategies/#full-reindexing)

> There are more than 5k records, but only 5k is added. Why is that?

For this I would double-check whether your plan allows for more than 5K records, I'd recommend reaching out to support@algolia.com for further help on this topic.

I hope this clarifies it.
I'll close this for now, but please do feel free to reopen if you experience further issues.
