### ISSUE TITLE
register decorator not working

### ISSUE THREAD

**Issue by dbinetti** [algolia/algoliasearch-django#295]
- Django version: 3.1
- Algolia Django integration version: 1.7.1
- Algolia Client Version: 1.20.0
- Language Version: 

### Description
The @register decorator does not appear to work.

### Steps To Reproduce

Use the @register decorator on an Index.
Run Django-admin algolia_reindex

Expect: "The following models were reindexed" with counts.

Get:  Nothing.

**Comment by watsonhaw5566** [comment]
Pleaes using Django>2.2,"algoliasearch-django" not don't support Django3

**Comment by tkrugg** [comment]
Hey @dbinetti would you be able to show us the code you've used for registering the model?
Or even better, an example of projects I can use to reproduce the issue?

FTR, django 3.x is officially supported since our latest release: https://github.com/algolia/algoliasearch-django/releases/tag/1.7.3, we're in the process of updating our docs to reflect it.
