### ISSUE TITLE
Make re-indexing configurable

### ISSUE THREAD

**Issue by arnaudlimbourg** [algolia/algoliasearch-django#8]
Hello,

The current implementation of reindex does a `Model.objects.all()`. I am talking about this [line](https://github.com/algolia/algoliasearch-django/blob/master/src/models.py#L215)

It would nice to have either this accept a different queryset so we could pass our own or have a different method.

Do you think that would make sense?

**Comment by dethi** [comment]
The problem is that the package is "state less". So, it would be difficult to ensure which record is currently indexed or not. I have the same problem with `should_index` ([see the comment](https://github.com/algolia/algoliasearch-django/blob/master/src/models.py#L173-L178)). I need to find a trick or maybe use the database.

Also, can you give me an example of when you would like to use a configurable reindex?

**Comment by arnaudlimbourg** [comment]
I hope the pull request shows what I am trying to achieve. Basically, I'd like to control more precisely what I want to index.

I would like to use the facilities provided by this package and since the reindex method does what I need to, except for the queryset.
